### ISSUE TITLE
AoT Build Error

### ISSUE THREAD

**Issue by maheshwarishivam** [mbenzenhoefer/ngx-bootstrap-growl#3]
I get following error while creating AoT build:

````
Error: Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /Users/shivam/www/personal/purdian/veto/node_modules/ng2-bootstrap-growl/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol Injectable in /Users/shivam/www/personal/purdian/veto/node_modules/ng2-bootstrap-growl/node_modules/@angular/core/src/di.d.ts, resolving symbol Injectable in /Users/shivam/www/personal/purdian/veto/node_modules/ng2-bootstrap-growl/node_modules/@angular/core/src/core.d.ts, resolving symbol Injectable in /Users/shivam/www/personal/purdian/veto/node_modules/ng2-bootstrap-growl/node_modules/@angular/core/index.d.ts, resolving symbol BootstrapGrowlService in /Users/shivam/www/personal/purdian/veto/node_modules/ng2-bootstrap-growl/src/bootstrap-growl.service.d.ts, resolving symbol BootstrapGrowlService in /Users/shivam/www/personal/purdian/veto/node_modules/ng2-bootstrap-growl/src/bootstrap-growl.service.d.ts
    at simplifyInContext (/Users/shivam/www/personal/purdian/veto/node_modules/@angular/compiler/bundles/compiler.umd.js:25569:27)
    at StaticReflector.simplify (/Users/shivam/www/personal/purdian/veto/node_modules/@angular/compiler/bundles/compiler.umd.js:25581:17)
    at StaticReflector.annotations (/Users/shivam/www/personal/purdian/veto/node_modules/@angular/compiler/bundles/compiler.umd.js:25077:64)
    at NgModuleResolver.resolve (/Users/shivam/www/personal/purdian/veto/node_modules/@angular/compiler/bundles/compiler.umd.js:17557:86)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/shivam/www/personal/purdian/veto/node_modules/@angular/compiler/bundles/compiler.umd.js:18058:64)
    at addNgModule (/Users/shivam/www/personal/purdian/veto/node_modules/@angular/compiler/bundles/compiler.umd.js:24839:62)
    at /Users/shivam/www/personal/purdian/veto/node_modules/@angular/compiler/bundles/compiler.umd.js:24850:18
    at Array.forEach (native)
    at _createNgModules (/Users/shivam/www/personal/purdian/veto/node_modules/@angular/compiler/bundles/compiler.umd.js:24849:30)
    at analyzeNgModules (/Users/shivam/www/personal/purdian/veto/node_modules/@angular/compiler/bundles/compiler.umd.js:24724:18)
    at analyzeAndValidateNgModules (/Users/shivam/www/personal/purdian/veto/node_modules/@angular/compiler/bundles/compiler.umd.js:24734:39)
    at AotCompiler.compileAll (/Users/shivam/www/personal/purdian/veto/node_modules/@angular/compiler/bundles/compiler.umd.js:24458:22)
    at CodeGenerator.codegen (/Users/shivam/www/personal/purdian/veto/modules/@angular/compiler-cli/src/codegen.ts:41:10)
    at /Users/shivam/www/personal/purdian/veto/node_modules/src/main.ts:20:84
    at Object.main (/Users/shivam/www/personal/purdian/tools/@angular/tsc-wrapped/src/main.ts:60:12)
    at Object.runInternal (/Users/shivam/www/personal/purdian/veto/node_modules/src/main.ts:25:10)
    at NgcWebpackPlugin.run (/Users/shivam/www/personal/purdian/veto/node_modules/src/plugin.ts:87:7)
    at Compiler.<anonymous> (/Users/shivam/www/personal/purdian/veto/node_modules/src/plugin.ts:73:53)
    at next (/Users/shivam/www/personal/purdian/veto/node_modules/tapable/lib/Tapable.js:140:14)
    at Compiler.<anonymous> (/Users/shivam/www/personal/purdian/veto/node_modules/awesome-typescript-loader/src/watch-mode.ts:7:13)
    at Compiler.applyPluginsAsyncSeries (/Users/shivam/www/personal/purdian/veto/node_modules/tapable/lib/Tapable.js:142:13)
    at /Users/shivam/www/personal/purdian/veto/node_modules/webpack/lib/Compiler.js:214:8
    at next (/Users/shivam/www/personal/purdian/veto/node_modules/tapable/lib/Tapable.js:138:11)
    at Compiler.compiler.plugin (/Users/shivam/www/personal/purdian/veto/node_modules/webpack/lib/node/NodeEnvironmentPlugin.js:21:4)
    at Compiler.applyPluginsAsyncSeries (/Users/shivam/www/personal/purdian/veto/node_modules/tapable/lib/Tapable.js:142:13)
    at Compiler.run (/Users/shivam/www/personal/purdian/veto/node_modules/webpack/lib/Compiler.js:211:7)
    at processOptions (/Users/shivam/www/personal/purdian/veto/node_modules/webpack/bin/webpack.js:359:12)
    at Object.<anonymous> (/Users/shivam/www/personal/purdian/veto/node_modules/webpack/bin/webpack.js:363:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
````

My `package.json` file:

````
{
  "name": "test-prj",
  "version": "0.0.1",
  "description": "Sample Project",
  "author": "Shivam Maheshwari",
  "dependencies": {
    "@angular/common": "2.4.4",
    "@angular/compiler": "2.4.4",
    "@angular/core": "2.4.4",
    "@angular/forms": "2.4.4",
    "@angular/http": "2.4.4",
    "@angular/platform-browser": "2.4.4",
    "@angular/platform-browser-dynamic": "2.4.4",
    "@angular/platform-server": "2.4.4",
    "@angular/router": "3.4.4",
    "@angularclass/conventions-loader": "^1.0.2",
    "@angularclass/hmr": "~1.2.2",
    "@angularclass/hmr-loader": "~3.0.2",
    "amcharts3": "github:amcharts/amcharts3",
    "ammap3": "github:amcharts/ammap3",
    "angular2-google-maps": "^0.17.0",
    "animate.css": "^3.5.1",
    "bootstrap": "4.0.0-alpha.4",
    "chart.js": "^1.1.1",
    "chartist": "^0.10.1",
    "ckeditor": "4.6.0",
    "core-js": "^2.4.1",
    "easy-pie-chart": "^2.1.7",
    "font-awesome": "^4.6.3",
    "font-awesome-sass-loader": "^1.0.2",
    "fullcalendar": "^2.7.2",
    "google-maps": "^3.2.1",
    "http-server": "^0.9.0",
    "ie-shim": "^0.1.0",
    "ionicons": "^2.0.1",
    "is-electron-renderer": "^2.0.0",
    "jquery": "https://registry.npmjs.org/jquery/-/jquery-2.2.4.tgz",
    "jquery-slimscroll": "^1.3.6",
    "leaflet": "^0.7.7",
    "leaflet-map": "^0.2.1",
    "lodash": "^4.12.0",
    "ng2-bootstrap": "^1.3.0",
    "ng2-bootstrap-growl": "0.0.5",
    "ng2-ckeditor": "1.1.5",
    "ng2-datetime": "^1.3.2",
    "ng2-smart-table": "^0.5.1-0",
    "ng2-tree": "^2.0.0-alpha.0",
    "ngx-uploader": "https://registry.npmjs.org/ngx-uploader/-/ngx-uploader-2.1.2.tgz",
    "normalize.css": "^4.1.1",
    "reflect-metadata": "^0.1.9",
    "rxjs": "~5.0.2",
    "tether": "^1.2.4",
    "zone.js": "~0.7.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "2.4.4",
    "@types/electron": "^1.3.20",
    "@types/fullcalendar": "^2.7.35",
    "@types/googlemaps": "^3.26.8",
    "@types/hammerjs": "^2.0.33",
    "@types/jquery": "https://registry.npmjs.org/@types/jquery/-/jquery-2.0.39.tgz",
    "@types/jquery ": "^2.0.33",
    "@types/jquery.slimscroll": "^1.3.30",
    "@types/lodash": "0.0.28",
    "@types/node": "^6.0.38",
    "@types/source-map": "^0.1.27",
    "@types/uglify-js": "^2.0.27",
    "@types/webpack": "^2.0.0",
    "add-asset-html-webpack-plugin": "^1.0.2",
    "angular2-template-loader": "^0.6.0",
    "assets-webpack-plugin": "^3.5.1",
    "awesome-typescript-loader": "~3.0.0-beta.18",
    "bootstrap-loader": "2.0.0-beta.18",
    "codelyzer": "~2.0.0-beta.4",
    "compression-webpack-plugin": "^0.3.1",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.26.1",
    "electron": "^1.4.0",
    "es6-promise": "^3.1.2",
    "es6-shim": "^0.35.0",
    "es7-reflect-metadata": "^1.6.0",
    "exports-loader": "^0.6.3",
    "expose-loader": "^0.7.1",
    "extract-text-webpack-plugin": "~2.0.0-beta.5",
    "file-loader": "^0.9.0",
    "find-root": "^1.0.0",
    "gh-pages": "^0.11.0",
    "html-webpack-plugin": "^2.26.0",
    "imports-loader": "^0.7.0",
    "json-loader": "^0.5.4",
    "ng-router-loader": "^2.1.0",
    "ngc-webpack": "^1.1.3",
    "node-sass": "^4.3.0",
    "npm-run-all": "^4.0.0",
    "optimize-js-plugin": "0.0.4",
    "parse5": "^3.0.1",
    "postcss-loader": "^1.0.0",
    "raw-loader": "0.5.1",
    "resolve-url-loader": "^1.4.3",
    "rimraf": "~2.5.4",
    "sass-loader": "^4.1.1",
    "script-ext-html-webpack-plugin": "^1.5.0",
    "source-map-loader": "^0.1.6",
    "string-replace-loader": "1.0.5",
    "style-loader": "^0.13.1",
    "to-string-loader": "^1.1.4",
    "ts-helpers": "1.1.2",
    "ts-node": "^2.0.0",
    "tslint": "~4.4.0",
    "typedoc": "^0.5.3",
    "typescript": "~2.1.5",
    "url-loader": "^0.5.7",
    "webpack": "2.2.0",
    "webpack-dashboard": "0.2.1",
    "webpack-dev-middleware": "1.9.0",
    "webpack-dev-server": "2.2.0",
    "webpack-dll-bundles-plugin": "^1.0.0-beta.5",
    "webpack-merge": "2.6.0"
  },
  "scripts": {
    "rimraf": "rimraf",
    "tslint": "tslint",
    "typedoc": "typedoc",
    "webpack": "webpack --progress --profile --bail",
    "webpack-dev-server": "webpack-dev-server",
    "webdriver-manager": "webdriver-manager",
    "clean": "npm cache clean && npm run rimraf -- node_modules doc coverage dist compiled dll",
    "clean:dist": "npm run rimraf -- dist",
    "clean:dll": "npm run rimraf -- dll",
    "clean:electron": "npm run rimraf -- build",
    "preclean:install": "npm run clean",
    "clean:install": "npm set progress=false && npm install",
    "preclean:start": "npm run clean",
    "clean:start": "npm start",
    "watch": "npm run watch:dev",
    "watch:dev": "npm run build:dev -- --watch",
    "watch:dev:hmr": "npm run watch:dev -- --hot",
    "watch:prod": "npm run build:prod -- --watch",
    "build": "npm run build:dev",
    "prebuild:dev": "npm run clean:dist",
    "build:dev": " npm run clean:dist && npm run webpack -- --config config/webpack.dev.js",
    "prebuild:prod": "npm run clean:dist",
    "build:prod": "npm run clean:dist && webpack --config config/webpack.prod.js  --progress --profile",
    "server": "npm run server:dev",
    "server:dev": "webpack-dev-server --config config/webpack.dev.js --progress --profile --watch --content-base src/",
    "server:dev:hmr": "npm run server:dev -- --inline --hot",
    "server:prod": "http-server dist -c-1 --cors",
    "server:test": "http-server dist-demo -c-1 --cors",
    "server:prod:ci": "http-server dist -p 3000 -c-1 --cors",
    "webdriver:update": "npm run webdriver-manager update",
    "webdriver:start": "npm run webdriver-manager start",
    "lint": "npm run tslint \"src/**/*.ts\" --force",
    "ngc": "./node_modules/.bin/ngc-w -p tsconfig.webpack.json",
    "pree2e": "npm run webdriver:update -- --standalone",
    "pretest": "npm run lint",
    "docs": "npm run typedoc -- --options typedoc.json --exclude '**/*.spec.ts' ./src/",
    "gh-pages": "wintersmith build -C docs && gh-pages -d docs/build",
    "start": "npm run server:dev",
    "start:hmr": "npm run server:dev:hmr",
    "version": "npm run build",
    "postversion": "git push && git push --tags",
    "build:electron": "npm run build:electron.full",
    "prebuild:electron.full": "npm run clean:electron",
    "build:electron.full": "npm run build:electron.renderer && npm run build:electron.main",
    "postbuild:electron.full": "npm run electron:start",
    "build:electron.renderer": "npm run webpack -- --config config/electron/webpack.renderer.prod.js",
    "build:electron.main": "npm run webpack -- --config config/electron/webpack.electron.prod.js",
    "electron:start": "electron build",
    "build:aot:prod": "npm run clean:dist && npm run clean:aot && webpack --config config/webpack.prod.js  --progress --profile --bail",
    "build:aot": "npm run build:aot:prod",
    "ci:aot": "npm run lint && npm run test && npm run build:aot && npm run e2e",
    "ci:jit": "npm run lint && npm run test && npm run build:prod && npm run e2e",
    "ci:nobuild": "npm run lint && npm test && npm run e2e",
    "ci:testall": "npm run lint && npm run test && npm run build:prod && npm run e2e && npm run build:aot && npm run e2e",
    "ci": "npm run ci:testall",
    "clean:aot": "npm run rimraf -- compiled",
    "e2e": "npm-run-all -p -r server:prod:ci e2e:only",
    "e2e:only": "npm run protractor"
  },
  "engines": {
    "node": ">= 5.4.1 < 7"
  }
}
````

**Comment by mbenzenhoefer** [comment]
Hi maheshwarishivam,
sorry for the late answer. Do you still experience this issue? I am not having this issue when running AOT build. Thanks

**Comment by dlusignan** [comment]
[at-loader] Checking finished with 2 errors
[at-loader] ./node_modules/ngx-bootstrap-growl/node_modules/rxjs/Subject.d.ts:16:22 
    TS2415: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'. 

[at-loader] ./node_modules/ngx-bootstrap-growl/node_modules/rxjs/observable/dom/WebSocketSubject.d.ts:23:22 
    TS2415: Class 'WebSocketSubject<T>' incorrectly extends base class 'AnonymousSubject<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => WebSocketSubject<R>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<T>'.
      Type 'WebSocketSubject<R>' is not assignable to type 'Observable<T>'.
        Types of property 'operator' are incompatible.
          Type 'Operator<any, R>' is not assignable to type 'Operator<any, T>'.
            Type 'R' is not assignable to type 'T'.
